a = input('Digite algo ')
print('as pções são?')
print('o tipo de dessa clase é: ', type(a))
print('so tem espaso? ', a.isspace())
print('é um numero? ', a.isnumeric())
print('é alfabetico? ', a.isalpha())
print('é alfanumerico? ', a.isalnum())
print('é so Maiúscula? ', a.isupper())
print('é so nimuscula? ', a.islower())
print('esta capitalizada? ', a.istitle())